import { mkdtemp, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, describe, expect, it } from 'vitest'
import { Context } from '@deepseek-ai/cordis'
import ToolRuntime from '@deepseek-ai/dsh-tools'
import SystemPrompt from '@deepseek-ai/dsh-system-prompt'
import LocalSubprocessRuntime from '@deepseek-ai/dsh-subprocess-local'
import LocalFileSystem from '@deepseek-ai/dsh-fs-local'
import LocalAttachmentStore from '@deepseek-ai/dsh-attachment-local'
import type { ContentBlock } from '@deepseek-ai/dsh-llm'
import * as ViewVideo from '../src/index.ts'
import { probeVideo, renderSheet } from '../src/ffmpeg.ts'
import { planSampling } from '../src/plan.ts'

/**
 * The assembled tool over a real ffmpeg. The encoder is the contract here —
 * a mocked one would assert this suite's own idea of a JPEG rather than that
 * a sheet actually renders — so every case drives the shipped binaries on a
 * clip generated by them.
 */

const temporaries: string[] = []

async function workspace(): Promise<string> {
  const dir = await mkdtemp(join(tmpdir(), 'dsh-view-video-'))
  temporaries.push(dir)
  return dir
}

/** Render a deterministic 2s/24fps clip with ffmpeg's own test source. */
async function clip(dir: string, name = 'clip.mp4', seconds = 2): Promise<string> {
  const path = join(dir, name)
  const ctx = new Context()
  await ctx.plugin(LocalSubprocessRuntime)
  await new Promise(resolve => setTimeout(resolve, 50))
  const handle = ctx.subprocess.spawn({
    argv: [
      'ffmpeg', '-v', 'error', '-y',
      '-f', 'lavfi', '-i', `testsrc=size=160x120:rate=24:duration=${seconds}`,
      '-c:v', 'libx264', '-pix_fmt', 'yuv420p', path,
    ],
    cwd: dir,
    stdio: { stdin: 'ignore', stdout: 'pipe', stderr: 'pipe' },
    graceMs: 2000,
  })
  const outcome = await handle.done
  if (outcome.exitCode !== 0) throw new Error(`fixture encode failed: exit ${String(outcome.exitCode)}`)
  return path
}

async function harness(cwd: string): Promise<Context> {
  const dshHome = await workspace()
  const ctx = new Context()
  await ctx.plugin(SystemPrompt)
  await ctx.plugin(ToolRuntime)
  await ctx.plugin(LocalSubprocessRuntime)
  await ctx.plugin(LocalFileSystem, { cwd })
  await ctx.plugin(LocalAttachmentStore, { dshHome })
  await ctx.plugin(ViewVideo, {})
  await new Promise(resolve => setTimeout(resolve, 100))
  return ctx
}

function textOf(content: readonly ContentBlock[]): string {
  return content.filter(block => block.type === 'text').map(block => block.text).join('\n')
}

async function call(ctx: Context, args: Record<string, unknown>) {
  return ctx.tools.execute({
    callId: 'call-1' as never,
    name: 'view_video',
    arguments: args,
    signal: new AbortController().signal,
  })
}

afterEach(async () => {
  await Promise.all(temporaries.splice(0).map(path => rm(path, { recursive: true, force: true })))
})

describe('view_video', () => {
  it('returns a rendered sheet as an image block beside its sampling report', async () => {
    const dir = await workspace()
    await clip(dir)
    const ctx = await harness(dir)
    const result = await call(ctx, { file_path: 'clip.mp4', count: 4 })

    expect(result.isError).toBe(false)
    const report = textOf(result.content)
    expect(report).toContain('160x120 h264')
    expect(report).toContain('<frames>0, 12, 24, 36</frames>')
    const image = result.content.find(block => block.type === 'image')
    expect(image?.attachment.mediaType).toBe('image/jpeg')
    expect(image?.attachment.bytes).toBeGreaterThan(0)
  })

  it('names the saved sheet after the clip and its frame span', async () => {
    const dir = await workspace()
    await clip(dir)
    const ctx = await harness(dir)
    const result = await call(ctx, { file_path: 'clip.mp4', count: 2 })
    const image = result.content.find(block => block.type === 'image')
    expect(image?.attachment.name).toBe('clip.mp4 f0-f24.jpg')
  })

  it('reaches every frame of a narrow window', async () => {
    const dir = await workspace()
    await clip(dir)
    const ctx = await harness(dir)
    const result = await call(ctx, { file_path: 'clip.mp4', start: 1, end: 1.25, count: 6 })
    expect(textOf(result.content)).toContain('stride=1: every source frame in this window is shown')
  })

  it('accepts a caption and an explicit layout', async () => {
    const dir = await workspace()
    await clip(dir)
    const ctx = await harness(dir)
    const result = await call(ctx, {
      file_path: 'clip.mp4', count: 2, columns: 2, tile_width: 120, label: 'pass: 1, of 2',
    })
    expect(result.isError).toBe(false)
    expect(textOf(result.content)).toContain('tiled 2x1')
  })

  it('refuses an empty path without touching the filesystem', async () => {
    const ctx = await harness(await workspace())
    const result = await call(ctx, { file_path: '   ' })
    expect(result.isError).toBe(true)
    expect(textOf(result.content)).toContain('file_path must be a non-empty string')
  })

  it('names the candidates it tried for a missing file', async () => {
    const dir = await workspace()
    const ctx = await harness(dir)
    const result = await call(ctx, { file_path: 'absent.mp4' })
    expect(result.isError).toBe(true)
    expect(textOf(result.content)).toContain('no such file (tried')
  })

  it('reports a file that carries no video stream', async () => {
    const dir = await workspace()
    await writeFile(join(dir, 'notes.mp4'), 'this is not a container')
    const ctx = await harness(dir)
    const result = await call(ctx, { file_path: 'notes.mp4' })
    expect(result.isError).toBe(true)
    expect(textOf(result.content)).toContain('cannot probe')
  })

  it('declares its presentation and scheduling without executing', () => {
    const ctx = new Context()
    const registered: {
      presentCall?: (args: unknown) => unknown
      isConcurrencySafe?: (args: unknown) => boolean
      output?: { render?: (args: unknown, value: unknown) => ContentBlock[] }
    }[] = []
    ctx.provide('tools', { register: (definition: never) => { registered.push(definition) } } as never)
    ViewVideo.apply(ctx, {})
    const definition = registered[0]
    expect(definition?.presentCall?.({ file_path: 'a.mp4' })).toEqual({
      card: 'generic',
      title: 'Watch video a.mp4',
      kind: 'read',
      locations: [{ path: 'a.mp4' }],
    })
    // Reading a video mutates nothing, so calls may be scheduled in parallel.
    // defineTool validates arguments first, so the probe passes a valid call.
    expect(definition?.isConcurrencySafe?.({ file_path: 'a.mp4' })).toBe(true)
    expect(definition?.isConcurrencySafe?.({})).toBe(false)

    // render() is the model-facing projection: report first, then the sheet.
    const rendered = definition?.output?.render?.({}, {
      path: '/clips/a.mp4',
      video: { width: 160, height: 120, codec: 'h264', fps: 24, duration: 2, frames: 48, bytes: 1 },
      sampling: { start: 0, end: 2, stride: 1, count: 1, cols: 1, rows: 1, picked: [0] },
      sheet: { attachmentId: 'sha256:x', mediaType: 'image/jpeg', bytes: 4, width: 8, height: 8, name: 'a.jpg' },
    })
    expect(rendered?.[0]).toMatchObject({ type: 'text' })
    expect(rendered?.[1]).toMatchObject({ type: 'image', attachment: { name: 'a.jpg' } })
  })

  it('omits an absent sheet name from the image block', () => {
    const ctx = new Context()
    const registered: { output?: { render?: (a: unknown, v: unknown) => ContentBlock[] } }[] = []
    ctx.provide('tools', { register: (definition: never) => { registered.push(definition) } } as never)
    ViewVideo.apply(ctx, {})
    const rendered = registered[0]?.output?.render?.({}, {
      path: '/clips/a.mp4',
      video: { width: 160, height: 120, codec: 'h264', fps: 0, duration: 0, frames: 0, bytes: 0 },
      sampling: { start: 0, end: 1, stride: 2, count: 1, cols: 1, rows: 1, picked: [0] },
      sheet: { attachmentId: 'sha256:y', mediaType: 'image/jpeg', bytes: 4, width: 8, height: 8 },
    })
    const image = rendered?.[1]
    expect(image?.type === 'image' && 'name' in image.attachment).toBe(false)
  })

  it('refuses a deployment whose attachment store rejects JPEG', async () => {
    const dir = await workspace()
    await clip(dir)
    const dshHome = await workspace()
    const ctx = new Context()
    await ctx.plugin(SystemPrompt)
    await ctx.plugin(ToolRuntime)
    await ctx.plugin(LocalSubprocessRuntime)
    await ctx.plugin(LocalFileSystem, { cwd: dir })
    await ctx.plugin(LocalAttachmentStore, { dshHome })
    await new Promise(resolve => setTimeout(resolve, 100))
    // A deployment may narrow its accepted raster types; the sheet is JPEG.
    Object.defineProperty(ctx.attachments, 'imageLimits', {
      value: { ...ctx.attachments.imageLimits, mediaTypes: ['image/png'] },
    })
    await ctx.plugin(ViewVideo, {})
    await new Promise(resolve => setTimeout(resolve, 50))
    const result = await call(ctx, { file_path: 'clip.mp4' })
    expect(result.isError).toBe(true)
    expect(textOf(result.content)).toContain('does not accept image/jpeg')
  })
})

describe('ffmpeg boundary', () => {
  it('refuses a sheet larger than the configured byte cap', async () => {
    const dir = await workspace()
    const path = await clip(dir)
    const ctx = new Context()
    await ctx.plugin(LocalSubprocessRuntime)
    await new Promise(resolve => setTimeout(resolve, 50))
    const video = await probeVideo(ctx, path, dir)
    const plan = planSampling({ count: 16 }, video)
    await expect(renderSheet(ctx, {
      path, cwd: dir, plan, video, quality: 2, maxBytes: 512, timeoutMs: 60_000,
    })).rejects.toThrow('stdout exceeded 512 bytes')
  })

  it('surfaces ffmpeg diagnostics for a window that selects no frame', async () => {
    const dir = await workspace()
    const path = await clip(dir)
    const ctx = new Context()
    await ctx.plugin(LocalSubprocessRuntime)
    await new Promise(resolve => setTimeout(resolve, 50))
    const video = await probeVideo(ctx, path, dir)
    // A window past the end of the clip selects nothing; ffmpeg fails the
    // encode rather than emitting an empty stream, so the caller sees its
    // diagnostics instead of a bare "no frames".
    const plan = { ...planSampling({}, video), start: 90, end: 95 }
    await expect(renderSheet(ctx, {
      path, cwd: dir, plan, video, quality: 4, maxBytes: 1 << 20, timeoutMs: 60_000,
    })).rejects.toThrow(/ffmpeg failed on/)
  })

  it('reports an unreadable container distinctly from a render failure', async () => {
    const dir = await workspace()
    const ctx = new Context()
    await ctx.plugin(LocalSubprocessRuntime)
    await new Promise(resolve => setTimeout(resolve, 50))
    await expect(probeVideo(ctx, join(dir, 'absent.mp4'), dir)).rejects.toThrow('cannot probe')
  })
})
